apiVersion: v1
kind: ConfigMap
metadata:
  name: app3s-config
data:
  APP_VERSION: 'alfa1'
  DB_HOST: '10.130.0.154'
  DB_DATABASE: '3s-homologacao'
  MAIL_FROM_ADDRESS: '3s-staging@noreply.unilab.edu.br'
  MAIL_FROM_NAME: '[HOMOLOGAÇÃO] 3S - Sistema de Solicitação de Serviço'
  APP_URL: 'https://3shomologacao.unilab.edu.br'
  LOG_LEVEL: 'debug'
  APP_DEBUG: 'true'